# generate settings
name: base7
gpu_ids: [0]
train: ~

# datasets
datasets:
  train:
    dataroot_HR: data/train_HR
    dataroot_LR: data/train_LR/XN
    filename_path: data/train.txt
    patch_size: 64
    batch_size: 16
    flip: true
    rot: true
    enlarge_times: 20
  val:
    dataroot_HR: data/train_HR
    dataroot_LR: data/train_LR/XN
    filename_path: data/val.txt
    enlarge_times: 1

# networks
networks:
  which_model: base7
  scale: 4
  in_channels: 3
  num_fea: 32
  m: 4
  out_channels: 3

# path to save
paths:
  experiment_root: ./experiment

# optimizer
solver:
  lr: !!float 1e-3
  lr_steps:
    - 120
    - 240
    - 360
    - 480
  lr_gamma: !!float 0.5
  loss: mix
  epochs: 100
  workers: 8
  val_step: 1
  resume: ~
  resume_path: ~
  qat: ~
  qat_path: ~
